import type { Prank } from './types'

export const PRANKS: Prank[] = [
  {
    id: 'slap',
    name: 'Office Slap',
    blurb: 'Open-palm performance review.',
    emoji: '👋',
    meltdown: 12,
    cooldownMs: 700,
    fx: 'slap',
    reaction: 'SLAP! A red handprint blooms. It is not going away.',
  },
  {
    id: 'kick',
    name: 'Cubicle Kick',
    blurb: 'Strategic shin diplomacy.',
    emoji: '👟',
    meltdown: 14,
    cooldownMs: 850,
    fx: 'kick',
    reaction: 'A sneaker-shaped welt. Hierarchy has a limp now.',
  },
  {
    id: 'haircut',
    name: 'Guerrilla Haircut',
    blurb: 'Scissors + zero consent.',
    emoji: '✂️',
    meltdown: 16,
    cooldownMs: 1100,
    fx: 'cut',
    hairDamage: 0.28,
    reaction: 'SNIP. Hair gone. Trauma permanent.',
  },
  {
    id: 'rubber-chicken',
    name: 'Rubber Chicken',
    blurb: 'Weaponized poultry.',
    emoji: '🐔',
    meltdown: 10,
    cooldownMs: 650,
    fx: 'chicken',
    reaction: 'BWOK. A poultry welt joins the collection.',
  },
  {
    id: 'coffee-spill',
    name: 'Coffee Flood',
    blurb: 'Scalding “oops.”',
    emoji: '☕',
    meltdown: 13,
    cooldownMs: 900,
    fx: 'spill',
    reaction: 'Brown stain locked in. Dry-cleaning will not save this.',
  },
  {
    id: 'pie-face',
    name: 'Pie of Doom',
    blurb: 'Cream. Chaos. Close-up.',
    emoji: '🥧',
    meltdown: 15,
    cooldownMs: 1000,
    fx: 'pie',
    reaction: 'Cream crust. They will taste vanilla until Q4.',
  },
  {
    id: 'stapler-slam',
    name: 'Stapler Slam',
    blurb: 'Giant cartoon stapler.',
    emoji: '📎',
    meltdown: 17,
    cooldownMs: 1200,
    fx: 'slam',
    reaction: 'KA-CHUNK. Forehead dimples of shame. Permanent.',
  },
  {
    id: 'void-memo',
    name: 'Void Memo',
    blurb: 'Subject: You never existed.',
    emoji: '📜',
    meltdown: 18,
    cooldownMs: 1300,
    fx: 'void',
    reaction: 'Reality cracks around them. Purple stress veins bloom.',
  },
]

export const MELTDOWN_GOAL = 100
